config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index"

  devise_for :users

  resources :projects do
    resources :tasks
  end

  resources :two_factors, only: [:create, :destroy]

  namespace :admin do
    resources :dashboard, only: [:index] do
    end

    resources :users, only: [:index, :update] do
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  before_validation :set_defaults

  enum :status, %i(ready active concluded)
  enum :department, %i(admin manager engineer qa)

  scope :accessible_to, -> (user) {
    if user.manager_or_above?
      all
    else
      where('department = ?', User.roles[user.role])
    end
  }

  private

  def set_defaults
    self.department = User.roles[:admin] unless self.department.present?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_manager_or_above!, only: %i[ new create destroy ]

  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  before_action :ensure_department!

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks.accessible_to(current_user)
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to(@task.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.organization.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
      set_current_task(@task)
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :project_id, :department)
    end
end

app/views/tasks/_form.html.erb
<%= form_for([@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: :true %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, options_for_select(Task.statuses.map{|k,_| [k,k]}, @task.status) %>
  </div>

  <div class="field">
    <%= f.label :department %><br />
    <% if current_user.manager_or_above? %>
      <%= f.select :department, options_for_select(User.roles.map{|k,_| [k,k]}, @task.department) %>
    <% else %>
      <%= f.select :department, options_for_select(User.roles.map{|k,_| [k,k]}, @task.department), {}, disabled: true %>
      (*) Only your manager can reasign this task
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mt-5" style="background: linear-gradient(to bottom, #ffffff 0%,#f0f8ff 100%);">
        <div class="card-body p-5">
          <h2 class="h3 mb-3 font-weight-normal text-center">Editing Task</h2>
            <%= render 'form' %>
        </div>
      </div>
      <div class="text-left mt-4">
        <%= link_to 'Show Task', [@task.project, @task], class: "btn btn-outline-info" %> 
        <%= link_to "Back to tasks", project_path(@task.project), class: "btn btn-outline-info" %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<% if @tasks.any? %>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Project</th>
      <th>Department</th>
      <th></th>
      <th></th>
      <% if current_user.manager_or_above? %>
        <th></th>
      <% end %>
    </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <td><%= task.status %></td>
      <td><%= task.project.name %></td>
      <td><%= task.department %></td>
      <td><%= link_to 'Show', [task.project, task] %></td>
      <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
      <% if current_user.manager_or_above? %>
        <td><%= link_to 'Delete', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
  </table>

<% else %>
  <b>No tasks yet</b>
<% end %>

<br />

<% if current_user.manager_or_above? %>
  <%= link_to 'New Task', new_project_task_path(params[:project_id]), class: "btn btn-outline-info", style: "color: #007bff;" %>
<% else %>
  <hr>
  <b>Ask your manager to create new tasks for this project</b>
<% end %>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 offset-md-3">
      <div class="card mb-2" style="background: linear-gradient(to bottom, #ffffff 0%,#f0f8ff 100%);">
        <div class="card-body ">
          <h1 class="mb-3 text-center">New task</h1>
          <%= render 'form' %><br>
          </div>
      </div>
       <%= link_to 'Back', project_tasks_path(@task.project), class: "btn btn-outline-info", style: "color: #007bff;" %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project.name %>
</p>

<p>
  <b>Department:</b>
  <%= @task.department %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task),class: "btn btn-outline-info" %> 
<%= link_to 'Back', project_tasks_path(@task.project), class: "btn btn-outline-info" %>