config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index"

  devise_for :users

  resources :projects do
    resources :tasks
  end

  resources :two_factors, only: [:create, :destroy]

  namespace :admin do
    resources :dashboard, only: [:index] do
    end

    resources :users, only: [:index, :update] do
    end
  end
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background: linear-gradient(to bottom, #ffffff 0%,#f0f8ff 100%); margin-bottom: 20px;">
  <%= link_to "Project Manager", root_path, class: "navbar-brand pl-3" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(projects_path) %>">
          <%= link_to "Projects", projects_path, class: "nav-link" %>
        </li>

        <% if current_user&.admin? %>
          <li class="nav-item <%= 'active' if current_page?(projects_path) %>">
            <%= link_to "Dashboard", admin_dashboard_index_path, class: "nav-link" %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "Account", edit_user_registration_path,
            class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path,
            data: { turbo_method: :delete },
            class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= render "layouts/header"%>
    <%= render "layouts/alerts"%>
    <%= yield %>
  </body>
</html>